### ISSUE TITLE
[BUG]: pybind11 does not build with `USE_SABI 3.9`

### ISSUE THREAD

**Issue by LecrisUT** [pybind/pybind11#5652]
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [x] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.13.6

### Problem description

When trying to build with
```cmake
pybind11_add_module(Spglib_python MODULE WITH_SOABI USE_SABI 3.9)
```
it fails when building with errors like
```
python3.13/site-packages/pybind11/include/pybind11/cast.h:1412:25: error: ‘PyTuple_SET_ITEM’ was not declared in this scope; did you mean ‘PyTuple_SetItem’?
   1412 |         PyTuple_SET_ITEM(result.ptr(), counter++, arg_value.release().ptr());
        |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |         PyTuple_SetItem
```

### Reproducible example code

```text
https://github.com/spglib/spglib/pull/577
The dependent PR introduced pybind11 and the PR above switched to using SABI
```

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by henryiii** [comment]
`USE_SABI` isn't an option to `pybind11_add_module`. pybind11 doesn't support the Limited API / Stable ABI yet (nanobind does), and when it does, 3.12 will be the oldest version we will be able to support since we added the features we need to the stable ABI in 3.12.

**Comment by henryiii** [comment]
(It's something we'd be happy to support, but it's likely a big project)
