### ISSUE TITLE
pybind11 not working with clang 10.0.0 and c++20: use of overloaded != operator is ambiguous

### ISSUE THREAD

**Issue by cstatz** [pybind/pybind11#2169]
## Issue description

I know it is early, but maybe someone has already seen this kind of error:

Just including pybind11 and trying to compile with clang 10.0.0 (the real one, not apple) and cpp-std=c++20 yields multiple errors of kind:

pybind11/cast.h:309:19: error: use of overloaded operator '!=' is ambiguous (with operand types 'pybind11::detail::values_and_holders::iterator' and 'pybind11::detail::values_and_holders::iterator') errors.

** Update: **  pybind11 version 2.5.0

## Expected behavior

The code compiles like is does with previous c++-standards.  

## Reproducible example code

clang++ -std=c++20 -I<pybind11include> -I<pythoninclude> -c main.cxx

The main.cxx just is:
#include <pybind11/pybind11.h>

[main.cxx.zip](https://github.com/pybind/pybind11/files/4487609/main.cxx.zip)

**Comment by wjakob** [comment]
@cstatz , can you post the complete warning message? There are probably more lines that show what declarations are now considered ambiguous with respect to each other.

**Comment by cstatz** [comment]
> @cstatz , can you post the complete warning message? There are probably more lines that show what declarations are now considered ambiguous with respect to each other.

Just plaintext here or as file?

**Comment by cstatz** [comment]
/usr/local/Cellar/llvm/10.0.0_1/bin/clang++ -std=c++2a -I/usr/local/include -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Headers/ -c main.cxx
In file included from main.cxx:1:
In file included from /usr/local/include/pybind11/pybind11.h:44:
In file included from /usr/local/include/pybind11/attr.h:13:
/usr/local/include/pybind11/cast.h:309:19: error: use of overloaded operator '!=' is ambiguous (with operand types 'pybind11::detail::values_and_holders::iterator' and 'pybind11::detail::values_and_holders::iterator')
        while (it != endit && it->type != find_type) ++it;
               ~~ ^  ~~~~~
/usr/local/include/pybind11/cast.h:292:14: note: candidate function
        bool operator!=(const iterator &other) { return curr.index != other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function
        bool operator==(const iterator &other) { return curr.index == other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function (with reversed parameter order)
/usr/local/include/pybind11/cast.h:333:12: error: use of overloaded operator '!=' is ambiguous (with operand types 'pybind11::detail::values_and_holders::iterator' and 'pybind11::detail::values_and_holders::iterator')
    if (it != vhs.end())
        ~~ ^  ~~~~~~~~~
/usr/local/include/pybind11/cast.h:292:14: note: candidate function
        bool operator!=(const iterator &other) { return curr.index != other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function
        bool operator==(const iterator &other) { return curr.index == other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function (with reversed parameter order)
/usr/local/include/pybind11/cast.h:461:22: error: use of overloaded operator '!=' is ambiguous (with operand types 'pybind11::detail::values_and_holders::iterator' and 'pybind11::detail::values_and_holders::iterator')
        for (auto vh : values_and_holders(it->second)) {
                     ^
/usr/local/include/pybind11/cast.h:292:14: note: candidate function
        bool operator!=(const iterator &other) { return curr.index != other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function
        bool operator==(const iterator &other) { return curr.index == other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function (with reversed parameter order)
/usr/local/include/pybind11/cast.h:461:24: note: in implicit call to 'operator!=' for iterator of type 'pybind11::detail::values_and_holders'
        for (auto vh : values_and_holders(it->second)) {
                       ^~~~~~~~~~~~~~~~~~
/usr/local/include/pybind11/cast.h:304:14: note: selected 'begin' function with iterator type 'pybind11::detail::values_and_holders::iterator'
    iterator begin() { return iterator(inst, &tinfo); }
             ^
In file included from main.cxx:1:
In file included from /usr/local/include/pybind11/pybind11.h:46:
/usr/local/include/pybind11/detail/class.h:319:20: error: use of overloaded operator '!=' is ambiguous (with operand types 'pybind11::detail::values_and_holders::iterator' and 'pybind11::detail::values_and_holders::iterator')
    for (auto &v_h : values_and_holders(instance)) {
                   ^
/usr/local/include/pybind11/cast.h:292:14: note: candidate function
        bool operator!=(const iterator &other) { return curr.index != other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function
        bool operator==(const iterator &other) { return curr.index == other.curr.index; }
             ^
/usr/local/include/pybind11/cast.h:291:14: note: candidate function (with reversed parameter order)
/usr/local/include/pybind11/detail/class.h:319:22: note: in implicit call to 'operator!=' for iterator of type 'pybind11::detail::values_and_holders'
    for (auto &v_h : values_and_holders(instance)) {
                     ^~~~~~~~~~~~~~~~~~
/usr/local/include/pybind11/cast.h:304:14: note: selected 'begin' function with iterator type 'pybind11::detail::values_and_holders::iterator'
    iterator begin() { return iterator(inst, &tinfo); }
             ^
4 errors generated

**Comment by cstatz** [comment]
Awesome! Thanks!
