### ISSUE TITLE
macos: C++11 flag not added, build errors

### ISSUE THREAD

**Issue by nschloe** [pybind/pybind11#2949]
I've now converted some of my projects to the new [`Pybind11Extension`](https://github.com/pybind/python_example). This saves me so much code, thank you!

I hit a wall with https://github.com/pyamg/pyamg/pull/272 though: It works well for builds on ubuntu-latest, but for macos-latest (10.15.*) the C++11 flag isn't added, resulting in [build errors](https://github.com/pyamg/pyamg/pull/272/checks?check_run_id=2340497334) like
```
 /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-qjkoia6h/overlay/lib/python3.6/site-packages/pybind11/include/pybind11/detail/common.h:392:15: error: unknown type name 'constexpr'
    inline static constexpr int log2(size_t n, int k = 0) { return (n <= 1) ? k : log2(n >> 1, k + 1); }
                  ^
```
Any hint on how to avoid those?

**Comment by henryiii** [comment]
I recommend adding the explicit keyword arg, `cxx_std=11`, that way you enforce an exact version instead of relying on the auto-search and not knowing what C++ version you are targeting. You can see how I [set it here](https://github.com/scikit-hep/boost-histogram/blob/develop/setup.py).

This might be buggy on macOS, though? Should always add at least the 11 flag when auto-searching...

**Comment by henryiii** [comment]
Your problem is that it's trying to build with `gcc`, which is a GCC 4.2 compatibility mode of clang; it does not support any C++ flags, so the auto search is correctly returning none. Why is it trying to build with GCC instead of clang?

**Comment by nschloe** [comment]
Thanks for taking a look! I'll look into it.

**Comment by nschloe** [comment]
I forced clang (12.0.0) on all platforms and the result is the same: https://github.com/pyamg/pyamg/pull/272/checks?check_run_id=2408093902#step:4:7421
```python
error: unknown type name 'constexpr'
```
