### ISSUE TITLE
Problem with std::shared_ptr<std::vector<T>> as argument in v2.2.0

### ISSUE THREAD

**Issue by pschella** [pybind/pybind11#1052]
Using `std::shared_ptr<std::vector<T>>` as an argument (or return value) used to work in v2.1.1, but now gives an error: 

`include/pybind11/cast.h:1378:5: error: static_assert failed "Holder classes are only supported for custom types"
    static_assert(std::is_base_of<base, type_caster<type>>::value`.

**Comment by dean0x7d** [comment]
Did this actually work or just compiler in v2.1.1? As far as I know, it never worked, it's just that it was a run-time error in v2.1 and a now it's a compile-time error in v2.2. There is an open issue about it: #787.

**Comment by pschella** [comment]
Ah, that could be. It is part of a long list of overloads that may not actually be used. Let me check.
