### ISSUE TITLE
[BUG]: Compilation failure with GCC 10.2 on pybind11 2.13.0 (typing.h, line 209)

### ISSUE THREAD

**Issue by zhqrbitee** [pybind/pybind11#5201]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.13.0

### Problem description

Environment:
-------------
Compiler: GCC 10.2
C++ Language Dialect: C++20 (std=c++20)

Error Message:
---------------

```
In file included from my_venv/include/pybind11/pybind11.h:19,
                 from my_venv/include/pybind11/numpy.h:12
my_venv/include/pybind11/typing.h:219:49: error: class template argument deduction failed:
  219 | struct handle_type_name<typing::Literal<Literals...>> {
      |                                                 ^~~
compilation terminated due to -Wfatal-errors.
```

It seems the error just comes from including pybind11 headers and it comes after upgrading to 2.13. 

```cpp
#if defined(__cpp_nontype_template_parameter_class)
template <typing::StringLiteral... Literals>
struct handle_type_name<typing::Literal<Literals...>> {
    static constexpr auto name = const_name("Literal[")
                                 + pybind11::detail::concat(const_name(Literals.name)...)
                                 + const_name("]");
};
template <typing::StringLiteral StrLit>
struct handle_type_name<typing::TypeVar<StrLit>> {
    static constexpr auto name = const_name(StrLit.name);
};
#endif
```

I see it tries to use the macro `__cpp_nontype_template_parameter_class` to enable some template codes. However not sure why the macro check is success, but GCC 10.2 fails to compile the codes.

### Is this a regression? Put the last known working version here if it is.

2.12.0

**Comment by henryiii** [comment]
> class template argument deduction failed

I assume it's trying to deduce something which means it's failing on a usage of it (and we test on GCC 10.2.1), so it's probably a regression for some usage. Do you know where this template is being used in your code?

**Comment by henryiii** [comment]
We might be missing a c++20 test on this compiler.

**Comment by rwgk** [comment]
It seems very likely to me that you're stumbling over a bug in that old GCC release. We're testing with C++20 using a variety of more modern C++ compilers (clang, gcc, msvc).

A simple, pragmatic workaround would be to add to the ifdef here:

https://github.com/pybind/pybind11/blob/57287b578d58af016cd571f6eacee19300d37f2d/include/pybind11/typing.h#L225

... && !defined(...conditions for GCC 10...)

But that wouldn't be covered by our GitHub Actions, which brings me to the question:

What platform do you have, and how exactly did you get your GCC 10? (Could we reproduce that with a GHA job, with a reasonable effort?)

@InvincibleRMC for awareness (and ideas).

**Comment by rwgk** [comment]
Oops, sorry, I just realized I mixed up clang 10 vs gcc 10 in my mind: we actually do have gcc 10 testing, e.g. here:

https://github.com/pybind/pybind11/actions/runs/9687720852/job/26732870800

It should be super easy to add gcc 10 C++20 testing along with the ifdef workaround. (Unless we're stumbling over other (presumed) bugs in the compiler.)

**Comment by InvincibleRMC** [comment]
@rwgk Do you want me to implement the suggest changes or are you on it?

**Comment by rwgk** [comment]
> @rwgk Do you want me to implement the suggest changes or are you on it?

It'd be helpful if you could send the PR. Thanks!
