### ISSUE TITLE
Compilation fails when using Eigen under Visual Studio + LLVM or Intel Toolchain

### ISSUE THREAD

**Issue by Baljak** [pybind/pybind11#1018]
When using a class containing an Eigen object (a VectorXd or MatrixD for example), it is not possible to compile under Visual Studio with LLVM or Intel Toolchain, we get the following error:

```
C:\Dev\libs\pybind11\include\pybind11/detail/common.h(664,92): error : 'type name' declared as a pointer to a reference of type 'remove_cv_t<const Eigen::Matrix<double, -1, 1, 0, -1, 1> &>' (aka 'const Eigen::Matrix<double, -1, 1, 0, -1, 1> &')
```

The following code illustrates the bug:

```c++
#include <pybind11/pybind11.h>
#include <pybind11/eigen.h>

namespace py = pybind11;

struct Vec
{
	Eigen::VectorXd v_;
};

PYBIND11_MODULE(test_eigen, m)
{
	py::class_<Vec>(m, "Vec")
		.def(py::init<>())
		.def_readwrite("v", &Vec::v_);

}
```
The problem comes from the fact that even if another toolchain is used, Visual Studio still defines `_MSC_VER`.

To correct it problem, I modified line 661 from `common.h` to this:

```c++
#if !defined(_MSC_VER) || defined(__clang__) || defined(__INTEL_COMPILER)
```

If there is no better way, I'll create a PR.

**Comment by dean0x7d** [comment]
As an alternative, can you try replacing `remove_cv_t` with `intrinsic_t` for both the `#if` and `#else` cases?

**Comment by Baljak** [comment]
I removed my patch and tried your suggestion and it works!

**Comment by dean0x7d** [comment]
Great! Do you want to turn that into a PR?

**Comment by Baljak** [comment]
Yes, thanks!

**Comment by dean0x7d** [comment]
BTW What has been your experience with Visual Studio + LLVM? I've been able to get part of pybind11's test suite to compile with VS/LLVM 4.0.1, but there are some strange runtime errors (looks related to exception handling).

**Comment by Baljak** [comment]
I don't have much experience with clang-cl at the moment. I decided to give it a try a few months ago and even managed to compile the entire Qt 5.8 framework (with the modification of a few files though).

While I didn't have any more success than you with pybind11 test suite, my current pybind11 project compiles and runs smoothly. As I will probably continue to use pybind11 with Visual Studio + LLVM in the near future, I might discover new issues and will hopefully be able to fix them.
