### ISSUE TITLE
PYBIND11_TYPE_CASTER(T, T::name) (name = static const char*) broken since v2.3

### ISSUE THREAD

**Issue by jokva** [pybind/pybind11#1927]
## Issue description

Creating type caster that look up the description compile-time broke with v2.3. I don't know if this is an intentional regression, or if using statically resolved strings was always broken.

I bisected it, and the change was introduced in c10ac6cf1f69ebe2b7dd26957325ea3b161cb7ff.

String literals still work, of course.

gcc complains:
```
error: no matching function for call to ‘_(const char* const&)’
     PYBIND11_TYPE_CASTER(Point, _(Point::name));
```

## Reproducible example code

```
struct custom {
    static constexpr auto name = "custom";
};

template < typename T >
struct caster {
    PYBIND11_TYPE_CASTER(T, _(T::name));
};

template <> struct type_caster< custom > : caster< custom > {};
```

edit: For completeness, a fully runnable example:

```
#include <pybind11/pybind11.h>

namespace py = pybind11;

struct custom {
    static constexpr auto name = "Custom";
};

namespace pybind11 { namespace detail {

template < typename T >
struct caster {
    PYBIND11_TYPE_CASTER(T, _(T::name));
};


template <> struct type_caster< custom > : caster< custom > {};

}} // namespace pybind11::detail

PYBIND11_MODULE(core, m) {
    py::class_< custom >(m, "cc");
}
```

PS. Sorry for the initially almost-empty issue, pressed submit by accident.

**Comment by wjakob** [comment]
You'll need to provide a reproducible example, the issue is not explained clearly enough.

**Comment by jokva** [comment]
Yes, I'm sorry, I hit the submit button by accident. I've updated the issue with the reproducible example, and the patch that triggers the issue.

**Comment by wjakob** [comment]
Did you mean to write
```
    PYBIND11_TYPE_CASTER(T, T::name);
```
?

**Comment by jokva** [comment]
Not really - in the actual codebase we also prefix the python name.

However, I just realised the example is incomplete, because it never tries to instantiate a signature.

```
#include <pybind11/pybind11.h>

namespace py = pybind11;

struct custom {
    static constexpr auto name = "Custom";
};

namespace pybind11 { namespace detail {

template < typename T >
struct caster {
    PYBIND11_TYPE_CASTER(T, _(T::name));
};


template <> struct type_caster< custom > : caster< custom > {};

}} // namespace pybind11::detail

PYBIND11_MODULE(core, m) {
    py::class_< custom >(m, "cc");
}

```

**Comment by wjakob** [comment]
You need to declare your string as follows:
```
    static constexpr const char name[] = "Custom";
```
Otherwise pybind11 doesn't know how long it is at compile time (it needs to be inferred from the type). All the documentation strings are now generated at compile time, which is no longer optional.

**Comment by jokva** [comment]
Thank you - there was a missing const when I tried name[].
