### ISSUE TITLE
[BUG]: Failed to build with gcc-4.x

### ISSUE THREAD

**Issue by hdu-sdlzx** [pybind/pybind11#5901]
### Required prerequisites

- [x] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

v3.0.1

### Problem description

The doc says:

Supported compilers
2. GCC 4.8 or newer

But actually pybind11 failed to compile with gcc-4.8.5:

$ g++ test.cpp -std=gnu++11 -I../pybind11/include -lpython3.8
In file included from ../pybind11/include/pybind11/detail/internals.h:12:0,
                 from ../pybind11/include/pybind11/detail/native_enum_data.h:9,
                 from ../pybind11/include/pybind11/cast.h:15,
                 from ../pybind11/include/pybind11/attr.h:14,
                 from ../pybind11/include/pybind11/detail/class.h:12,
                 from ../pybind11/include/pybind11/pybind11.h:12,
                 from test.cpp:1:
../pybind11/include/pybind11/conduit/pybind11_platform_abi_id.h:75:10: error: #error "Unknown platform or compiler: PLEASE REVISE THIS CODE."
 #        error "Unknown platform or compiler: PLEASE REVISE THIS CODE."
          ^

This error is generated because _GLIBCXX_USE_CXX11_ABI which is introduced in gcc-5.x is not defined.
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Are we going to fix gcc-4.x or raise the platform requirements?

### Reproducible example code

```text
#include "pybind11/pybind11.h"

int main()
{
    return 0;
}
```

### Is this a regression? Put the last known working version here if it is.

v2.13.6

**Comment by hdu-sdlzx** [comment]
Still failed to build when -D_GLIBCXX_USE_CXX11_ABI is added:

$ g++ test.cpp -std=gnu++11 -I../pybind11/include -D_GLIBCXX_USE_CXX11_ABI -lpython3.8
In file included from ../pybind11/include/pybind11/attr.h:13:0,
                 from ../pybind11/include/pybind11/detail/class.h:12,
                 from ../pybind11/include/pybind11/pybind11.h:12,
                 from test.cpp:1:
../pybind11/include/pybind11/detail/common.h:209:49: error: missing binary operator before token "("
     && ((defined(__has_include) && __has_include(<string_view>)) || defined(_MSC_VER))
                                                 ^
If __has_include is not defined, the compiler should stop at "defined(__has_include)" but actually it does not.
This looks like a c preprocessor bug.

**Comment by hdu-sdlzx** [comment]
The following change worked.

diff --git a/include/pybind11/conduit/pybind11_platform_abi_id.h b/include/pybind11/conduit/pybind11_platform_abi_id.h
index d21fdc56..93d45c31 100644
--- a/include/pybind11/conduit/pybind11_platform_abi_id.h
+++ b/include/pybind11/conduit/pybind11_platform_abi_id.h
@@ -71,6 +71,8 @@
 #        define PYBIND11_BUILD_ABI                                                                \
             "_libstdcpp_gxx_abi_1xxx_use_cxx11_abi_" PYBIND11_PLATFORM_ABI_ID_TOSTRING(           \
                 _GLIBCXX_USE_CXX11_ABI)
+#    elif defined(__GNUC__) && (__GNUC__ < 5)
+#            define PYBIND11_BUILD_ABI "_gcc_4.x"
 #    else
 #        error "Unknown platform or compiler: PLEASE REVISE THIS CODE."
 #    endif
diff --git a/include/pybind11/detail/common.h b/include/pybind11/detail/common.h
index 314dba40..2b0d897e 100644
--- a/include/pybind11/detail/common.h
+++ b/include/pybind11/detail/common.h
@@ -205,9 +205,10 @@
 #    define PYBIND11_HAS_VARIANT 1
 #endif

-#if defined(PYBIND11_CPP17)                                                                       \
-    && ((defined(__has_include) && __has_include(<string_view>)) || defined(_MSC_VER))
-#    define PYBIND11_HAS_STRING_VIEW 1
+#if defined(PYBIND11_CPP17)
+#    if (defined(__has_include) && __has_include(<string_view>)) || defined(_MSC_VER)
+#        define PYBIND11_HAS_STRING_VIEW 1
+#    endif
 #endif

 #if (defined(PYPY_VERSION) || defined(GRAALVM_PYTHON)) && !defined(PYBIND11_SIMPLE_GIL_MANAGEMENT)

**Comment by rwgk** [comment]
The documentation isn't accurate anymore, this just escaped everyone's attention.

The way I usually think about it:

* We really only support what we test.

Currently that's:

```
     93 MSVC 19.44.35219.0
     42 GNU 15.2.0
      1 GNU 14.2.0
      7 GNU 13.4.0
     82 GNU 13.3.0
      7 GNU 11.5.0
      8 GNU 11.4.0
     14 GNU 10.5.0
      2 GNU 10.2.1
      7 GNU 9.5.0
      7 GNU 8.5.0
     37 AppleClang 17.0.0.17000013
     26 AppleClang 15.0.0.15000100
     14 Intel 2021.10.0.20230609
      7 NVHPC 23.5.0
      7 Clang 21.1.0 with GNU-like command-line
      7 Clang 18.1.8
      7 Clang 16.0.6
      7 Clang 14.0.6
      7 Clang 11.1.0
      7 Clang 5.0.2
```

This counts how often cmake's `The CXX compiler identification is ...` appears in the CI logs.

According to https://gcc.gnu.org/releases.html, even GCC 5 was released already more than 10 years ago.

It's a real burden to have to support such ancient compilers. I actually hope we'll drop C++ 11 and C++ 14 support sometime soon.

How much of a hardship is it for you to just keep using pybind11 2.13.6?

**Comment by rwgk** [comment]
From the issue description:
> The doc says:
> Supported compilers
> 2. GCC 4.8 or newer

This reflects reality more accurately:

* https://github.com/pybind/pybind11/pull/5910

**Comment by hdu-sdlzx** [comment]
Thank you for your reply.

> How much of a hardship is it for you to just keep using pybind11 2.13.6?

I have no problem keep using pybind 2.x with old compilers. An updated doc is enough for me, thank you!
