### ISSUE TITLE
Upgrading to 2 leads to: Unknown/invalid class_ template parameters provided

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [pybind/pybind11#909]
I am trying to upgrade to 2.x but new template magic leads to incomprehensible template error stacks: `Unknown/invalid class_ template parameters provided`.
 This seems to have been introduced in 5fffe200e337f1a1bb13034fac29a63ad6eae304.

I have 2 issues with this:

1. I am puzzled whether this really is the user experience that pybind11 wants to provide to users. The error message conveys near zero information. I am wondering whether this code has been reviewed?

2. Also the new `class_` API is not well documented.
  There seems to be no description what the upgrade path from the old API is or what traits the new API awaits.

As a result, can someone explain what the upgrade path for the following code from:

    void bindMyResource(py::module& m) {
        py::class_<MyResource, IntrusivePtr<MyResource>>(m, "Model", py::base<Resource>);
    }

to:

    void bindMyResource(py::module& m) {
        py::class_<MyResource, IntrusivePtr<MyResource>>(m, "Model", /*probably some type that gets passed in here*/);
    }

or:

    void bindMyResource(py::module& m) {
        py::class_<MyResource, Resource, IntrusivePtr<MyResource>>(m, "Model");
    }

is? Thanks.

**Comment by jagerman** [comment]
Both approaches are valid.  The rational for allowing the template arguments to be specified in any order is that it allows other things (such as the base class) to be specified as a template argument, and makes the template arguments position-independent.

It seems more likely that are are [missing a `PYBIND11_DECLARE_HOLDER_TYPE`](http://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#custom-smart-pointers) for your holder type; in 2.0 that is now detected as a compilation error; before 2.0 it wasn't caught but could fail in unpredictable ways.

**Comment by jagerman** [comment]
Closing this due to lack of response.  (Feel free to reopen if this is still an issue.)
