### PR TITLE
Add note that VS2017 requires /permissive- to build in C++17 mode

### LINKED ISSUE #2089: Pybind fails to build with MSVC 19.16 in C++17 mode
## Fails to build with MSVC 19.16.27034.0 in C++17
I used pybind v 2.4.3

> cmake -G Ninja -DPYBIND11_CPP_STANDARD=/std:c++17 ..\src
> ninja

Error:
> D:\Libs\Pybind\2.4.3\src\include\pybind11/stl_bind.h(415): error C2893: Failed to specialize function template 'enable_if<_Test,_Ty>::type pybind11::detail::vector_buffer(Class_ &)'
        with
        [
            _Ty=void
        ]

No problem with the default c++14 mode.

Great library, BTW! 😃 👍

### PR DESCRIPTION
**Pull request by YannickJadoul**
As discussed on #2089, this (finally) adds a note to the docs that C++17 mode in VS2017 requires the /permissive- flag.

Closes #2089
Closes #2292﻿

### CODE REVIEW

**Comment by YannickJadoul** [comment]
I can't find any other place to add this. I'd have thought this was something to add to the FAQ page, but no existing section seemed fitting. But I'm open to suggestions.

**Comment by bstaletic** [comment]
Why not the README? It's where all the supported compilers are mentioned.

**Comment by YannickJadoul** [comment]
> Why not the README? It's where all the supported compilers are mentioned.

The readme currently only contains the minimal version of the compilers (and very summarized; "Microsoft Visual Studio 2015 Update 3 or newer"). Neither VS 2017 nor C++17 are minimal requirements for pybind11, so I was hesitant to throw in those extra lines there? You can still compile perfectly in C++14 mode in VS 2017.

**Comment by henryiii** [comment]
I've simplified the matrix by dropping a few extra arguments. We can still get the "max C++" setting by manually placing the CXX standard flag in args2. I'm about to make the setup a little more complicated by putting the dev flag back in.

**Comment by YannickJadoul** [comment]
Amazing! Thanks again, @henryiii! :-)
