### ISSUE TITLE
Pybind11 no longer compiles with GCC 7.2 and Python 2.7

### ISSUE THREAD

**Issue by MichaelGoulding** [pybind/pybind11#1804]
## Pybind11 no longer compiles with GCC and Python 2.7

I get the following errors when compiling with v2.3.0:

```
In file included from /home/thedude/Anaconda43/include/python2.7/Python.h:8:0,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/detail/common.h:112,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pytypes.h:12,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/cast.h:13,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/attr.h:13,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pybind11.h:49,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../shared/PythonDef.h:17,
                 from /mnt/_work/10/s/code/Binaries/exe/stdafx.h:6,
                 from /mnt/_work/10/s/code/Binaries/exe/src/exe.cpp:6:
/home/thedude/Anaconda43/include/python2.7/pyconfig.h:1190:0: error: "_POSIX_C_SOURCE" redefined [-Werror]
 #define _POSIX_C_SOURCE 200112L
 
In file included from /usr/include/x86_64-linux-gnu/c++/7/bits/os_defines.h:39:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h:533,
                 from /usr/include/c++/7/cxxabi.h:49,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pybind11.h:45,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../shared/PythonDef.h:17,
                 from /mnt/_work/10/s/code/Binaries/exe/stdafx.h:6,
                 from /mnt/_work/10/s/code/Binaries/exe/src/exe.cpp:6:
/usr/include/features.h:265:0: note: this is the location of the previous definition
 # define _POSIX_C_SOURCE 200809L
 
In file included from /home/thedude/Anaconda43/include/python2.7/Python.h:8:0,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/detail/common.h:112,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pytypes.h:12,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/cast.h:13,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/attr.h:13,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pybind11.h:49,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../shared/PythonDef.h:17,
                 from /mnt/_work/10/s/code/Binaries/exe/stdafx.h:6,
                 from /mnt/_work/10/s/code/Binaries/exe/src/exe.cpp:6:
/home/thedude/Anaconda43/include/python2.7/pyconfig.h:1212:0: error: "_XOPEN_SOURCE" redefined [-Werror]
 #define _XOPEN_SOURCE 600
 
In file included from /usr/include/x86_64-linux-gnu/c++/7/bits/os_defines.h:39:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h:533,
                 from /usr/include/c++/7/cxxabi.h:49,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../thirdparty/pybind11/include/pybind11/pybind11.h:45,
                 from /mnt/_work/10/s/code/Binaries/exe/../../../shared/PythonDef.h:17,
                 from /mnt/_work/10/s/code/Binaries/exe/stdafx.h:6,
                 from /mnt/_work/10/s/code/Binaries/exe/src/exe.cpp:6:
/usr/include/features.h:202:0: note: this is the location of the previous definition
 # define _XOPEN_SOURCE 700
```

I believe this is introduced by commit: [69dc380](https://github.com/pybind/pybind11/commit/69dc380c0dcb3ee057165844f270c48a1b98c625)

**Comment by wjakob** [comment]
Hi Michael,

our travis CI suite tests GCC on Linux, with Python 2.7, which at least seems to pass the test suite:

https://travis-ci.org/pybind/pybind11/jobs/544890337

Can you clarify on how your setup is different?

Best,
Wenzel

**Comment by wjakob** [comment]
btw, these are actually warnings that get turned into errors due to your addition of a -Werror flag.

**Comment by wjakob** [comment]
One option might be to simply include that header a few lines before. Does the following patch fix things?
```
patch
diff --git a/include/pybind11/pybind11.h b/include/pybind11/pybind11.h
index f1d91c7..0cc5dd5 100644
--- a/include/pybind11/pybind11.h
+++ b/include/pybind11/pybind11.h
@@ -41,16 +41,15 @@
 #  endif
 #endif
 
-#if defined(__GNUG__) && !defined(__clang__)
- #include <cxxabi.h>
-#endif
-
-
 #include "attr.h"
 #include "options.h"
 #include "detail/class.h"
 #include "detail/init.h"
 
+#if defined(__GNUG__) && !defined(__clang__)
+#  include <cxxabi.h>
+#endif
+
 NAMESPACE_BEGIN(PYBIND11_NAMESPACE)
 
 /// Wraps an arbitrary C++ function/method/lambda function/.. into a callable Python object
```

**Comment by MichaelGoulding** [comment]
We are using GCC version 7.2.  Perhaps that is the difference.

**Comment by MichaelGoulding** [comment]
Yes, that patch fixes things.

**Comment by wjakob** [comment]
Merged, will be part of v2.3.1

**Comment by henryiii** [comment]
Updated to 2.3.0 and this killed my tests (with `-Werror` on). Glad to see it's fixed. Thanks!
