### ISSUE TITLE
Class with deleted "operator delete" and std::unique_ptr<..., nodelete>

### ISSUE THREAD

**Issue by BorisSchaeling** [pybind/pybind11#1291]
Is this code supposed to compile? 

```
#include <pybind11/pybind11.h>
#include <memory>

using namespace pybind11;

struct S
{
  void operator delete(void*) = delete;
};

PYBIND11_MODULE(example, m)
{
  class_<S, std::unique_ptr<S, nodelete>> s{ m, "S" };
}
```

I'm asking as I get a compile error with Visual Studio 2017 15.5.6 (latest version as of today). The code compiles fine with g++ 6.4.0 and clang 5.0.1. 

This is the VS2017 compile error: 

> include\pybind11\pybind11.h(986): error C2280: 'void S::operator delete(void *)': attempting to reference a deleted function

Line 986 in pybind11.h refers to one of the call_operator_delete() functions. All call_operator_delete() functions expect to be able to call "operator delete". It's not surprising that this doesn't work in the example above as "operator delete" has been deleted. But as the example does compile with g++ and clang and as I use pybind11::nodelete, I would assume something else goes wrong and VS2017 should actually never try to use those call_operator_delete() functions?

**Comment by jagerman** [comment]
Is this a new failure in 15.5.6?  That definitely smells like a bug.

**Comment by BorisSchaeling** [comment]
I know that VS2017 15.5.5 doesn't compile the code either. But 15.5.5 is also a very recent version (from January 25). I had no time yet to dive deeper into the pybind11 code to have a look at what VS2017 does differently than g++ and clang. I quickly tried compiling the example with C++14 and C++17 support enabled but that didn't change anything.

**Comment by BorisSchaeling** [comment]
I managed to create a test case which doesn't depend on pybind11 and which compiles with g++ 6.4.0 and clang 5.0.1 but not with VS2017 15.5.6: 

```
#include <type_traits>
#include <cstddef>

using namespace std;

struct S
{
  void operator delete(void*) = delete;
  void operator delete(void*, std::size_t) = delete;
};

template <class T, typename SFINAE = void> struct has_operator_delete : std::false_type { };
template <class T> class has_operator_delete<T, void_t<
  decltype(static_cast<void(*)(void*)>(T::operator delete))>> : std::true_type { };

template <class T, class SFINAE = void> struct has_operator_delete_size : std::false_type { };
template <class T> struct has_operator_delete_size<T, void_t<
  decltype(static_cast<void(*)(void*, std::size_t)>(T::operator delete))>> : std::true_type { };

int main()
{
  static_assert(!has_operator_delete<S>::value);
  static_assert(!has_operator_delete_size<S>::value);
}
```

With VS2017 15.5.6 both asserts fail. [I reported the issue to Microsoft.](https://developercommunity.visualstudio.com/content/problem/201249/sfinae-failure-with-void-t-decltype-and-operator-d.html)

**Comment by juliangaal** [comment]
Any update on this? I am running into similar issues with clang->=8

**Comment by BorisSchaeling** [comment]
Microsoft fixed the bug in their compiler (I can confirm that I can successfully compile the test case above with VS2017 15.8.5). If you have a similar problem with another compiler, I recommend reaching out to the compiler developers.
