### ISSUE TITLE
[BUG]: overload cast for function with template option failing on clang

### ISSUE THREAD

**Issue by briha** [pybind/pybind11#4649]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.10.4

### Problem description

`py::overload_cast` fails to compile on `AppleClang 14.0.0.14000029` (it does compile on GCC) for a member function that has both a template version, and a non-template version taking an argument. 

```cpp
struct Foo {
    void bar();
    void bar(int x);
}
```
where
```cpp
.def("bar", py::overload_cast<int>(&Foo::bar));
```
fails on Clang, and compiles on GCC. The equivalent `static_cast` compiles on both
```cpp
.def("bar", static_cast<void (Foo::*) (int)>(&Foo::bar));
```

```log
[ 50%] Building CXX object CMakeFiles/pybind_template_mwe.dir/main.cpp.o
pybind_template_mwe/main.cpp:14:21: error: no matching function for call to object of type 'const detail::overload_cast_impl<int>'
        .def("bar", py::overload_cast<int>(&Foo::bar));
                    ^~~~~~~~~~~~~~~~~~~~~~
include/pybind11/detail/common.h:1076:20: note: candidate template ignored: couldn't infer template argument 'Return'
    constexpr auto operator()(Return (*pf)(Args...)) const noexcept -> decltype(pf) {
                   ^
include/pybind11/detail/common.h:1081:20: note: candidate template ignored: couldn't infer template argument 'Return'
    constexpr auto operator()(Return (Class::*pmf)(Args...), std::false_type = {}) const noexcept
                   ^
include/pybind11/detail/common.h:1087:20: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    constexpr auto operator()(Return (Class::*pmf)(Args...) const, std::true_type) const noexcept
                   ^
1 error generated.
```

### Reproducible example code

```text
#include <iostream>
#include <pybind11/pybind11.h>

namespace py = pybind11;

struct Foo {
    template <typename T>
    void bar() { std::cout << "bar() with template" << std::endl; }
    void bar(int x) { std::cout << "bar(int)" << std::endl; }
};

PYBIND11_MODULE(pybind_template_mwe, m) {
    py::class_<Foo>(m, "Foo")
        .def("bar", py::overload_cast<int>(&Foo::bar));
//        .def("bar", static_cast<void (Foo::*) (int)>(&Foo::bar));  // this works on clang, too
}
```

### Is this a regression? Put the last known working version here if it is.

Not a regression
