### PR TITLE
Numpy: better compilation errors, long double support

### PR DESCRIPTION
**Pull request by jagerman**
A few small-ish changes related to numpy:

- the dtype declaration macro documentation was unclear
- non-POD types resulted in non-obvious compilation errors (changed to a static_assert)
- added `long double` (and `std::complex<long double>`) support: there's not a huge reason to *not* support them--supporting all floating point types makes the code a little cleaner--and this allows binding of Eigen code that has long doubles.

The changes to the numpy dtype test script also resolve the linux/i386 test failure from #612.

### CODE REVIEW

**Comment by aldanor** [comment]
Looks all good to me. Just wondering, why the `=` to `^` change for unaligned fields?

**Comment by jagerman** [comment]
Two reasons: first `^` is basically the unaligned version of the default `@`, but more importantly, `^` lets the numpy-specific `g`, `F`, `D`, and `G` through.  (Without it, `g` isn't supported at all, and the capital complex ones need to be `Zf`, `Zd`).

**Comment by aldanor** [comment]
Oh, I see, good then. Can't remember to have encountered `^` in format strings myself, but it looks like that's the proper choice here.

File: include/pybind11/numpy.h [hunk 1]
```diff
@@ -220,6 +219,16 @@ inline bool check_flags(const void* ptr, int flag) {
...
 }
 
+template <typename T> struct is_std_array : std::false_type { };
+template <typename T, size_t N> struct is_std_array<std::array<T, N>> : std::true_type { };
+template <typename T> struct is_complex : std::false_type { };
+template <typename T> struct is_complex<std::complex<T>> : std::true_type { };
+
+template <typename T> using is_pod_struct = all_of<
+    std::is_pod<T>, // offsetof only works correctly for POD types
+    is_none_of<T, std::is_reference, std::is_array, is_std_array, std::is_arithmetic, is_complex, std::is_enum>
```
Comment (dean0x7d) [inline include/pybind11/numpy.h]: Why is specifically `std::array` disallowed?

File: include/pybind11/numpy.h [hunk 2]
```diff
@@ -220,6 +219,16 @@ inline bool check_flags(const void* ptr, int flag) {
     return (flag == (array_proxy(ptr)->flags & flag));
 }
 
+template <typename T> struct is_std_array : std::false_type { };
+template <typename T, size_t N> struct is_std_array<std::array<T, N>> : std::true_type { };
+template <typename T> struct is_complex : std::false_type { };
+template <typename T> struct is_complex<std::complex<T>> : std::true_type { };
+
+template <typename T> using is_pod_struct = all_of<
+    std::is_pod<T>, // offsetof only works correctly for POD types
```
Comment (dean0x7d) [inline include/pybind11/numpy.h]: Nitpicking: `offsetof` only needs `is_standard_layout`, it's numpy that needs the rest of `is_pod`.

File: include/pybind11/numpy.h (hunk 1 above)
Comment (jagerman) [inline include/pybind11/numpy.h]: Because it was before.  (I didn't change the logic here, just cleaned it up a bit with convenience meta-templates).  I seem to recall some discussion about coming back to handle that eventually (cc @aldanor?) at some point post 2.0.

File: include/pybind11/numpy.h (hunk 2 above)
Comment (jagerman) [inline include/pybind11/numpy.h]: I just copied the comment, but I'll update it.

File: include/pybind11/common.h [hunk 3]
```diff
@@ -406,6 +406,10 @@ template <class... Ts> using any_of = std::disjunction<Ts...>;
 #endif
 template <class... Ts> using none_of = negation<any_of<Ts...>>;
 
+template <class T, template<class> class... Predicates> using is_all_of = all_of<Predicates<T>...>;
+template <class T, template<class> class... Predicates> using is_any_of = any_of<Predicates<T>...>;
+template <class T, template<class> class... Predicates> using is_none_of = none_of<Predicates<T>...>;
```
Comment (jagerman) [inline include/pybind11/common.h]: Ah, good suggestion.

**Comment by jagerman** [comment]
Not sure how I accidentally undid the DECL_NPY_API ones, but I fixed that too (and squashed everything).

**Comment by wjakob** [comment]
Looks all good, thank you!
