### ISSUE TITLE
doesn't compile with Clang 3.4

### ISSUE THREAD

**Issue by wojdyr** [pybind/pybind11#5341]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.13.5

### Problem description

I suppose Clang 3.4 is not widely used anymore, but just to let you know.
I tried building my bindings on an old system with Clang 3.4 and I got:

```
include/pybind11/detail/type_caster_base.h:260:9: error: 
      return type 'pybind11::handle' must match previous return type 'const pybind11::handle' when
      lambda expression has unspecified explicit return type
        return handle();
        ^
```
It's this lambda:
https://github.com/pybind/pybind11/blob/3fb16ad17587a7ad7fbe18c043e790d68ee7fab4/include/pybind11/detail/type_caster_base.h#L251-L261

After adding `-> handle` as the return type, the compiler was satisfied and I didn't come across any other problems.

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by henryiii** [comment]
:robot: _AI text below_ :robot:

The lambda named in this report no longer mixes return types; #5494 (15d9dae1) rewrote it. Note also that Clang 3.4 is outside the supported compiler matrix, so we cannot test it.

If you can still reproduce this with current master (v3), please comment and we can reopen.
