### PR TITLE
Bug fixes: Add missing `handle_type_name` specializations.

### PR DESCRIPTION
**Pull request by rwgk**
## Description
This PR adds a number of missing `handle_type_name` specializations that have accumulated over time unnoticed, until work under #4888 exposed the issue. This PR is based on #4888, but omits behavior changes other than the pure bug fixes.

To prevent future accumulation of missing `handle_type_name` specializations, this PR adds the `-DPYBIND11_DISABLE_HANDLE_TYPE_NAME_DEFAULT_IMPLEMENTATION` cmake option, which is `OFF` by default, but set to `ON` for some (but not all) ci.yml jobs. When `ON`, missing `handle_type_name` specializations trigger compilation errors.

The `quote_cpp_type_name()` function introduced in #4888 is included here, but with the implementation changed to a no-op. This pin-points where C++ type names "slip through" (and could confuse stubgen), and enables easy future experimentation similar to #4888.

Caveat: The test coverage for the `handle_type_name` specializations is incomplete: while the `-DPYBIND11_DISABLE_HANDLE_TYPE_NAME_DEFAULT_IMPLEMENTATION` option ensures that no specializations are missing, some of the `name`s could be changed without triggering unit test failures.

## Suggested changelog entry:

```rst

```

### CODE REVIEW

**Comment by rwgk** [comment]
@henryiii It's past bedtime in my time zone. I'll look at the GHA results tomorrow.

Current thinking based on the hope that the GHA results look good:

* With `-DPYBIND11_DISABLE_HANDLE_TYPE_NAME_DEFAULT_IMPLEMENTATION=ON` (default is `OFF`) we can be sure that we're not missing any specializations.

* But full test coverage for all specializations is still missing. I believe it's at least a couple hours of leg work to achieve full coverage. Do we really need it? The specializations are pretty trivial: are code reviews sufficient?

**Comment by rwgk** [comment]
@henryiii The PR description is complete now, with "Caveat" regarding unit test coverage.

I believe it's a minor caveat and we should include these bug fixes in the release as is. Or I could work on making the unit test coverage complete over the weekend, and we release next week.

File: CMakeLists.txt [hunk 1]
```diff
@@ -107,6 +107,8 @@ endif()
 option(PYBIND11_INSTALL "Install pybind11 header files?" ${PYBIND11_MASTER_PROJECT})
 option(PYBIND11_TEST "Build pybind11 test suite?" ${PYBIND11_MASTER_PROJECT})
 option(PYBIND11_NOPYTHON "Disable search for Python" OFF)
+option(PYBIND11_DISABLE_HANDLE_TYPE_NAME_DEFAULT_IMPLEMENTATION
+       "To enforce that a handle_type_name<> specialization exists" OFF)
```
Comment (henryiii) [inline CMakeLists.txt:111]: Should we indicate that this is an internal option, and maybe even hide it? Users aren't expected to use this or rely on it existing.

**Review by henryiii — APPROVED** [review]
Otherwise, I think this is fine. We don't have 100% coverage currently, and we've often focused on keeping the test suite compile time down in the past over complete coverage, so I think it's fine to not worry about covering every new specialization. I'd like to have seen a small smattering of them added (like 3), but at least the anyset one is there.

File: CMakeLists.txt (hunk 1 above)
Comment (rwgk) [reply CMakeLists.txt:111]: I could be useful, for others to discover missing specializations, e.g. if I wanted to clean up the Google codebase:

https://github.com/pybind/pybind11/pull/4888#issuecomment-1871790589

Ultimately these are real bugs that erode type checking completeness.

I wouldn't go as far as prominently advertising the option (I figure most people don't have time to clean up things like this), but I also wouldn't want to hide it.

Comment (henryiii) [reply CMakeLists.txt:111]: Okay.
