### ISSUE TITLE
Can't bind copy constructors for some classes in 2.2

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1114]
Dear Pybind11 developers,

I am working on upgrading my project to use v2.2 of pybind11 and stumble on the following problem: for some template types attempts to bind copy-constructor lead to a compilation error. I have tried tried to reproduce this error with a dummy example of user defined types but was not suspenseful (error was not triggered) so i am posting example that uses `std::` class:
```C++
#include <pybind11/pybind11.h>

PYBIND11_PLUGIN(example) {
    pybind11::module m("example", "pybind11 example plugin");

	pybind11::class_<std::binary_function<double,double,bool>, std::shared_ptr<std::binary_function<double,double,bool>>> cl(m, "binary_function_double_double_bool_t", "");

	cl.def(pybind11::init<>());
	cl.def(pybind11::init<const struct std::binary_function<double, double, bool> &>(), pybind11::arg(""));

    return m.ptr();
}
```

Compilation error:
```
In file included from arg-forwarding.cpp:1:
In file included from /home/benchmark/src/pybind11/include/pybind11/pybind11.h:46:
/home/benchmark/src/pybind11/include/pybind11/detail/init.h:164:46: error: excess elements in struct initializer
            v_h.value_ptr() = new Cpp<Class>{std::forward<Args>(args)...};
                                             ^~~~~~~~~~~~~~~~~~~~~~~~
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:1108:14: note: in instantiation of function template specialization 'pybind11::detail::initimpl::constructor<const std::binary_function<double, double, bool>
      &>::execute<pybind11::class_<std::binary_function<double, double, bool>, std::shared_ptr<std::binary_function<double, double, bool> > >, pybind11::arg, 0>' requested here
        init.execute(*this, extra...);
             ^
arg-forwarding.cpp:9:5: note: in instantiation of function template specialization 'pybind11::class_<std::binary_function<double, double, bool>, std::shared_ptr<std::binary_function<double, double, bool> > >::def<const
      std::binary_function<double, double, bool> &, pybind11::arg>' requested here
        cl.def(pybind11::init<const struct std::binary_function<double, double, bool> &>(), pybind11::arg(""));
           ^
1 warning and 1 error generated.
```

**Comment by YannickJadoul** [comment]
Seems this has got something to do with the brace-initialization of `py::init`, but 1) `std::binary_function` has been deprecated since C++11 so I guess it won't optimally collaborate with the C++11 and C++14 features of pybind11, and 2) if I look at the definition, `std::binary_function` is actually just an empty struct with a few typedefs, so what is the point of constructing it?

Apart from that, the actual problem is the following, I would guess: pybind want to initialize the new class as `new Cpp<Class>{std::forward<Args>(args)...}` which would be `new std::binary_function<double, double, bool>{ other }` where `other` has type `const std::binary_function<double, double, bool> &`. Since it is a POD (an empty struct, no specific constructor, ...), the brace initialization wants to member-wise initialize the struct, but you're passing 1 argument while the struct only has 0 members. Hence the error `excess elements in struct initializer`.

The workaround is to `py::init([](const std::binary_function<double, double, bool> & other) { return new std::binary_function<double, double, bool>(other); })` (where you can choose to use `()` instead of `{}`). 

See also #1070. So maybe it would be an idea for pybind11 to provide some kind of a tag to `init` that could switch between brace-initialization and parentheses-calls?

**Comment by lyskov** [comment]
Thank you for looking this up @YannickJadoul ! Unfortunately problem is not specific to `std::binary_function`, it was just first piece of code that failed.

I working on a Binder project (https://github.com/RosettaCommons/binder) which automatically generate binding code. And while i can certainly implement lambda workaround for this it seems quite wasteful to me since we will have to generate one extra function for each class (and in my current project that mean ~6k extra functions). So i wanted to double check: would it be possible to implement workaround for this on Pybind11 level or you think that will not be practical?

Thanks,

**Comment by bstaletic** [comment]
The example code from the OP works in pybind 2.5. Closing.
