### ISSUE TITLE
Overriding function that return a reference lead to a compilation error

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#392]
Hi Wenzel, I just noticed that recent Pybind11 master can no longer compile code that tries to overriding function that return a reference (i quite sure its worked a few months back). Please see example to trigger this and error message below.
Thanks,

```c++
#include <pybind11/pybind11.h>

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);


class OverrideTest
{
public:
	int a;

	// overriding this works fine
	virtual int foo_v() { return a; }

	// overriding this give compilation error
	virtual int & foo() { return a; }
};


struct PyCallBack_OverrideTest : public OverrideTest {
	using OverrideTest::OverrideTest;

	int foo_v() override {
		PYBIND11_OVERLOAD_NAME(int, OverrideTest, "foo_v", OverrideTest::foo_v);
	}

	int & foo() override {
		using int_r = int &;
		PYBIND11_OVERLOAD_NAME(int_r, OverrideTest, "foo", OverrideTest::foo);
	}
};


namespace py = pybind11;

PYBIND11_PLUGIN(example) {
    py::module m("example", "pybind11 example plugin");

	{
		pybind11::class_<OverrideTest, std::shared_ptr<OverrideTest>, PyCallBack_OverrideTest> cl(m, "OverrideTest");
		pybind11::handle cl_type = cl;

		cl.def(pybind11::init<>());

		cl.def("foo_v",&OverrideTest::foo_v);

		cl.def("foo",&OverrideTest::foo);
	}

    return m.ptr();
}
```

Compilation error message:
```
pybind11/include/pybind11/cast.h:273:19: error: multiple overloads of 'cast' instantiate to the same signature 'pybind11::handle (int &&, pybind11::return_value_policy, pybind11::handle)'
    static handle cast(type &&src, return_value_policy policy, handle parent) {
                  ^
...src/pybind11/include/pybind11/cast.h:313:77: note: in instantiation of template class 'pybind11::detail::type_caster_base<int &>' requested here
template <typename type, typename SFINAE = void> class type_caster : public type_caster_base<type> { };
                                                                            ^
...src/pybind11/include/pybind11/cast.h:840:61: note: in instantiation of template class 'pybind11::detail::type_caster<int &, void>' requested here
        std::is_same<decltype(std::declval<type_caster<T>>().operator T&()), T&>::value
                                                            ^
...src/pybind11/include/pybind11/cast.h:837:30: note: during template argument deduction for class template partial specialization 'move_always<type-parameter-0-0, typename enable_if<move_is_plain_type<T>::value &&
      !std::is_copy_constructible<T>::value && std::is_move_constructible<T>::value && std::is_same<decltype(std::declval<type_caster<T> >().operator T &()), T &>::value, void>::type>' [with T = int &]
template <typename T> struct move_always<T, typename std::enable_if<
                             ^
...src/pybind11/include/pybind11/cast.h:910:87: note: while substituting explicitly-specified template arguments into function template 'cast'
template <typename T> typename std::enable_if<detail::move_always<T>::value, T>::type cast(object &&object) {
                                                                                      ^
python-override.cpp:28:3: note: in instantiation of function template specialization 'pybind11::object::cast<int &>' requested here
                PYBIND11_OVERLOAD_NAME(int_r, OverrideTest, "foo", OverrideTest::foo);
                ^
...src/pybind11/include/pybind11/pybind11.h:1438:5: note: expanded from macro 'PYBIND11_OVERLOAD_NAME'
    PYBIND11_OVERLOAD_INT(ret_type, cname, name, __VA_ARGS__) \
    ^
...src/pybind11/include/pybind11/pybind11.h:1435:51: note: expanded from macro 'PYBIND11_OVERLOAD_INT'
            return overload(__VA_ARGS__).template cast<ret_type>();  }
                                                  ^
...src/pybind11/include/pybind11/cast.h:267:19: note: previous declaration is here
    static handle cast(const type &src, return_value_policy policy, handle parent) {
                  ^
...src/pybind11/include/pybind11/cast.h:279:35: error: 'src' declared as a pointer to a reference of type 'int &'
    static handle cast(const type *src, return_value_policy policy, handle parent) {
                                  ^
...src/pybind11/include/pybind11/cast.h:287:18: error: 'operator type-parameter-0-0 *' declared as a pointer to a reference of type 'int &'
    operator type*() { return (type *) value; }
                 ^
3 errors generated.
```

**Comment by wjakob** [comment]
Hi Sergey,

I don't think that such overrides will work for elementary types like ``int`` for implementation reasons (this would entail returning a reference to a local variable holding the value extracted from the Python function -- but that variable doesn't exist anymore at that point).

However, all of this should work for custom types where it's actually possible to return a reference (e.g. when replacing "int" by "A" for a hypothetical "struct A { }" in the above example). That said, it doesn't work (anymore) -- it looks like this is a regression introduced in ed14879a1942fdfa4e4ef053c842841ca9fd6fc4 (cc @jagerman).

-Wenzel

**Comment by jagerman** [comment]
I'm looking into it.

**Comment by lyskov** [comment]
Right, the actual bug in PyRosetta was indeed some function that return class by reference. It just when i created the minimal example it got err *simplified* - sorry about that!

**Comment by jagerman** [comment]
Well, the simplification exposed another problem--namely that in your original example, we allow returning an `int &`, even though it's a referencing a member of a temporary variable, so I guess that was helpful anyway.

**Comment by lyskov** [comment]
Great, thank you for takin care of this so quickly!!! I am going to test this now!

**Comment by lyskov** [comment]
Hmm... @jagerman it looks like that attempt to return std::string & is now lead to `Unable to cast type to reference: value is local to type caster` this is not correct behavior right?

**Comment by jagerman** [comment]
What's the context in which you're getting it?

**Comment by jagerman** [comment]
With #394 merged, you'll get that error now if you do `obj.cast<std::string &>()` or `py::cast<std::string &>(obj)` (or call something that invokes one of those).  What was happening before, though, is that you'd get an std::string& reference, but it's a reference to an object that has already been deleted: we only have an std::string instance for the duration of the `cast` call.

You can see this yourself with the following code, using either v1.8.1, or master with just the first commit of #394 applied, using this code:
```C++
#include <pybind11/pybind11.h>
PYBIND11_PLUGIN(t) {
    namespace py = pybind11;
    py::module m("t");
    m.def("foo", [](py::object o) { std::cout << o.cast<std::string &>() << "\n"; });
    return m.ptr();
}
```
and this python:
```Python
import t
t.foo("asdf" * 10)
```
That gives me output of some random garbage, followed by a few (but not all) of the `asdf`'s; here's the output run through `xxd`:

```
00000000: 884b e87d 897f 0000 c07b 7a02 0000 0000  .K.}.....{z.....
00000010: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000020: 6173 6466 6173 6466 0a                   asdfasdf.
```
and here's the output if I drop the `&` from the cast:
```
00000000: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000010: 6173 6466 6173 6466 6173 6466 6173 6466  asdfasdfasdfasdf
00000020: 6173 6466 6173 6466 0a                   asdfasdf.
```

So this is definitely correct *now*, and was definitely not correct before.

**Comment by lyskov** [comment]
OK, in understand that, but could this be fixed so function returning references to a string objects could be overridden? It would be a pity if we can't handle functions returning references to standard strings since there is a lot of C++ code thats is full of such functions.

**Comment by lyskov** [comment]
I am guessing that the core of this problem is because std::string is automatically mapped to a Python string, is this so? Can this be overridden? For example by adding `PYBIND11_MAKE_OPAQUE(std::string);`? (btw i tried that and it lead to a compilation error)

**Comment by jagerman** [comment]
Yes, that's the problem.  When you do a `obj->cast<std::string &>`, pybind11 creates a new `std::string`, copying the string value of the python object wrapped by `obj`, then returns that new object.  Since there is no actually `std::string` instance stored anywhere, we can't return a reference or pointer to one.

> It would be a pity if we can't handle functions returning references to standard strings since there is a lot of C++ code thats is full of such functions.

I agree.  I've filed #397 to discuss/track it.
