### PR TITLE
Silence Clang 10 compiler warnings. Fixes #2225.

### LINKED ISSUE #2225: New warnings with Clang10
## Issue description

After upgrading to Clang10 I see new warnings (which result in errors due to `-Werror`) on my builds with pybind11 2.5.0:
```
/home/florian/sources/bap_server/so/pybind11/include/pybind11/pybind11.h:1093:9: error: expression result unused [-Werror,-Wunused-value]
        PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/florian/sources/bap_server/so/pybind11/include/pybind11/detail/common.h:662:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
#define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                              ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/florian/sources/bap_server/so/gina/gina.cpp:176:4: note: in instantiation of function template specialization 'pybind11::class_<bap::GINACallbackWrapper>::class_<>' requested here
   py::class_<bap::GINACallbackWrapper>(m, "GINACallbackWrapper").def("callback", &bap::GINACallbackWrapper::callback);
```

## Reproducible example code

As far as I can see this would happen for every usage of `class_` and should immediately show up as soon as Clang10 is used and `-Wunused-value` is enabled. I was able to locally disable it via:
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-value"
        /* Register base classes specified via template arguments to class_, if any */
        PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
#pragma clang diagnostic pop
```

### PR DESCRIPTION
**Pull request by apollo13**

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Tests pass, I don't see how this could do anything wrong.

Thanks for both reporting as well as for making the PR, @apollo13! :-)
