### PR TITLE
fix: add guard for GCC <10.3 on C++20

### LINKED ISSUE #5201: [BUG]: Compilation failure with GCC 10.2 on pybind11 2.13.0 (typing.h, line 209)
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.13.0

### Problem description

Environment:
-------------
Compiler: GCC 10.2
C++ Language Dialect: C++20 (std=c++20)

Error Message:
---------------

```
In file included from my_venv/include/pybind11/pybind11.h:19,
                 from my_venv/include/pybind11/numpy.h:12
my_venv/include/pybind11/typing.h:219:49: error: class template argument deduction failed:
  219 | struct handle_type_name<typing::Literal<Literals...>> {
      |                                                 ^~~
compilation terminated due to -Wfatal-errors.
```

It seems the error just comes from including pybind11 headers and it comes after upgrading to 2.13. 

```cpp
#if defined(__cpp_nontype_template_parameter_class)
template <typing::StringLiteral... Literals>
struct handle_type_name<typing::Literal<Literals...>> {
    static constexpr auto name = const_name("Literal[")
                                 + pybind11::detail::concat(const_name(Literals.name)...)
                                 + const_name("]");
};
template <typing::StringLiteral StrLit>
struct handle_type_name<typing::TypeVar<StrLit>> {
    static constexpr auto name = const_name(StrLit.name);
};
#endif
```

I see it tries to use the macro `__cpp_nontype_template_parameter_class` to enable some template codes. However not sure why the macro check is success, but GCC 10.2 fails to compile the codes.

### Reproducible example code

_No response_

### Is this a regression? Put the last known working version here if it is.

2.12.0

### PR DESCRIPTION
**Pull request by InvincibleRMC**
## Description

Fixes #5201 and updates CI.

## Suggested changelog entry:

```rst
   Fix regression introduced in #5201 for GCC<10.3 in C++20 mode.
```

### CODE REVIEW

**Comment by InvincibleRMC** [comment]
Let me know if it is desired to store the guard somewhere else and have it reference or just having 4 instances of the guard is fine.

**Comment by InvincibleRMC** [comment]
Also please let me know if you want to test on gcc 10.1 or 10.2 if that is even possible.

**Comment by rwgk** [comment]
AFK for a few more hours, can't look at code until then, but: let's not do
anything complicated. Low hanging fruits will do. IMO

**Comment by rwgk** [comment]
> Let me know if it is desired to store the guard somewhere else and have it referenced or just having 4 instances of the guard is fine.

Yeah, that was a bit much of duplicated code, but it's very easily avoided. I went ahead and did that. Thanks for creating this PR, from there it was very quick.

**Review by rwgk — APPROVED** [review]
