### ISSUE TITLE
[BUG]: invalid use of incomplete type when importing pybind11.h on 3.11

### ISSUE THREAD

**Issue by oscargus** [pybind/pybind11#4464]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

2.8.1

### Problem description

When trying to build my package on 3.11 I get an error which seems to relate to pybind11.h. It works on 3.6 through 3.10.

```
 In file included from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/cast.h:16:0,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/attr.h:13,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pybind11.h:13,
                   from /local/data1/B-ASIC/src/simulation.hpp:5,
                   from /local/data1/B-ASIC/src/main.cpp:1:
  /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
  /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject {aka struct _frame}’
               frame = frame->f_back;
                            ^~
  In file included from /local/data1/miniconda3/envs/py311/include/python3.11/Python.h:42:0,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/detail/common.h:186,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pytypes.h:12,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/cast.h:13,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/attr.h:13,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pybind11.h:13,
                   from /local/data1/B-ASIC/src/simulation.hpp:5,
                   from /local/data1/B-ASIC/src/main.cpp:1:
  /local/data1/miniconda3/envs/py311/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject {aka struct _frame}’
   typedef struct _frame PyFrameObject;
                  ^~~~~~
  In file included from /local/data1/miniconda3/envs/py311/include/python3.11/Python.h:38:0,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/detail/common.h:186,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pytypes.h:12,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/cast.h:13,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/attr.h:13,
                   from /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pybind11.h:13,
                   from /local/data1/B-ASIC/src/simulation.hpp:5,
                   from /local/data1/B-ASIC/src/main.cpp:1:
  /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pybind11.h: In function ‘pybind11::function pybind11::detail::get_type_override(const void*, const pybind11::detail::type_info*, const char*)’:
  /tmp/tmpp10bx8jg.build-temp/_deps/pybind11-src/include/pybind11/pybind11.h:2348:29: error: ‘PyCodeObject {aka struct PyCodeObject}’ has no member named ‘co_varnames’; did you mean ‘co_names’?
                       locals, PyTuple_GET_ITEM(f_code->co_varnames, 0)
                               ^
  gmake[2]: *** [CMakeFiles/_b_asic.dir/build.make:83: CMakeFiles/_b_asic.dir/src/main.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:191: CMakeFiles/_b_asic.dir/all] Error 2
  gmake: *** [Makefile:104: all] Error 2
```

This happens both with GCC 7.3.1 and Python 3.11.0 (CentOS 7) and GCC 10.2.1 and Python 3.11.1 (local GitLab CI, some Debian).

I am fully open to the fact that I may have some strange setup.py (which I have not written myself and have limited knowledge of). I note, however, that it is not using PyBind11Extension, but its own subclassed extension to run cmake (not that long and AFAIK nothing "strange").

The first lines of simulation.hpp are
```
 #ifndef ASIC_SIMULATION_HPP
#define ASIC_SIMULATION_HPP

#define NOMINMAX
#include <pybind11/pybind11.h>
```
so nothing strange happens that that should obviously affect pybind11.h

I'll add the error I get on Windows 11 in a separate post.

### Is this a regression? Put the last known working version here if it is.

Not a regression

**Comment by oscargus** [comment]
On Windows 11 with MSVC 19.33.31630.0 and Python 3.11.0 I get

```
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\detail/type_caster_base.h(482,26): error C2027: use of undefined type '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\pytypedefs.h(22): message : see declaration of '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\detail/type_caster_base.h(482,26): error C2027: use of undefined type '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\pytypedefs.h(22): message : see declaration of '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\detail/type_caster_base.h(482,26): error C2027: use of undefined type '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\pytypedefs.h(22): message : see declaration of '_frame' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:/Users/Oscar/AppData/Local/Temp/tmp68yhmkt_.build-temp/Release/_deps/pybind11-src/include\pybind11/pybind11.h(2348,29): error C2039: 'co_varnames': is not a member of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\cpython/code.h(103): message : see declaration of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:/Users/Oscar/AppData/Local/Temp/tmp68yhmkt_.build-temp/Release/_deps/pybind11-src/include\pybind11/pybind11.h(2347,41): error C2660: 'pybind11::detail::dict_getitem': function does not take 1 arguments (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pytypes.h(562,19): message : see declaration of 'pybind11::detail::dict_getitem' (compiling source file C:\Users\Oscar\B-ASIC\src\main.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pybind11.h(2348,29): error C2039: 'co_varnames': is not a member of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\cpython/code.h(103): message : see declaration of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pybind11.h(2347,41): error C2660: 'pybind11::detail::dict_getitem': function does not take 1 arguments (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pytypes.h(562,19): message : see declaration of 'pybind11::detail::dict_getitem' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\run.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pybind11.h(2348,29): error C2039: 'co_varnames': is not a member of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\miniconda3\envs\py311\include\cpython/code.h(103): message : see declaration of 'PyCodeObject' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pybind11.h(2347,41): error C2660: 'pybind11::detail::dict_getitem': function does not take 1 arguments (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
  C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_deps\pybind11-src\include\pybind11\pytypes.h(562,19): message : see declaration of 'pybind11::detail::dict_getitem' (compiling source file C:\Users\Oscar\B-ASIC\src\simulation\compile.cpp) [C:\Users\Oscar\AppData\Local\Temp\tmp68yhmkt_.build-temp\Release\_b_asic.vcxproj]
```

Here, `use of undefined type '_frame'` and `'co_varnames': is not a member of 'PyCodeObject'` are similar to the previous error messages.

**Comment by oscargus** [comment]
Just in case someone runs into this.

The problem turned out to be that the CMake-files did point to a specific commit to fetch (2.8.1 which did not have Python 3.11 support).

**Comment by Enough7** [comment]
> Just in case someone runs into this.

How do you fix this? I am on commit `8de7772c`

**Comment by Enough7** [comment]
See [riebl/artery #297](https://github.com/riebl/artery/issues/297#issue-1813569195) on how I fixed it
