### ISSUE TITLE
Problem with shared_ptr<T const>

### ISSUE THREAD

**Issue by cjdrake** [pybind/pybind11#131]
Hello, first I want to thank the author(s) for working on this neat library. When it works for me, it's quite magical.

I'm working on a pybind11 module here:
https://github.com/cjdrake/boolexpr/blob/pybind11/python/boolexprmodule.cc

When I try to compile with GCC 5.3.1, I get the following error:
```
boolexprmodule.cc:63:77:   required from here
../third_party/pybind11/include/pybind11/pybind11.h:867:13: error: no matching function for call to 'std::shared_ptr<const boolexpr::Atom>::shared_ptr(std::shared_ptr<boolexpr::BoolExpr>)'
             new (&inst->holder) holder_type(inst->value->shared_from_this());
             ^
```

The reason I suspect there's a bug is that it can't find a matching function call for `std::shared_ptr<boolexpr::BoolExpr>`. But I'm not using that holder anywhere in my code or the pybind11 module. I'm using `std::shared_ptr<boolexpr::BoolExpr const>`.

The compiler error only happens when I uncomment line 63, the `Atom` class that is derived from `BoolExpr`. I'm hoping I just made some simple mistake, and you can help me with the correct documentation, but I just can't make it work.

**Comment by wjakob** [comment]
Hi,

I'd be happy to take a look, but can you isolate the issue into something small and self-contained? (also, so that it can be turned into a testcase). See some of the closed issue tickets for reference.

Wenzel

**Comment by cjdrake** [comment]
This snippet seems to cause the same issue:

```c++
#include <memory>
#include <pybind11/pybind11.h>

namespace py = pybind11;

class Foo : public std::enable_shared_from_this<Foo> {};
class Bar : public Foo {};

PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T const>);

PYBIND11_PLUGIN(foo) {
    py::module m("foo", "Test Case");

    py::class_<Foo, std::shared_ptr<Foo const>> cls_foo(m, "Foo");
    py::class_<Bar, std::shared_ptr<Bar const>> cls_bar(m, "Bar", cls_foo);

    return m.ptr();
}
```

```
foomod.cc:15:74:   required from here
../third_party/pybind11/include/pybind11/pybind11.h:867:13: error: no matching function for call to 'std::shared_ptr<const Bar>::shared_ptr(std::shared_ptr<Foo>)'
             new (&inst->holder) holder_type(inst->value->shared_from_this());
             ^
```

**Comment by cjdrake** [comment]
I should note that changing the definition of class `Foo` to this:

```c++
class Foo : public std::enable_shared_from_this<Foo const> {};
```

Changes the error message to this:

```
foomod.cc:15:74:   required from here
../third_party/pybind11/include/pybind11/pybind11.h:867:13: error: no matching function for call to 'std::shared_ptr<const Bar>::shared_ptr(std::shared_ptr<const Foo>)'
             new (&inst->holder) holder_type(inst->value->shared_from_this());
             ^
```

**Comment by wjakob** [comment]
Fixed in 309a85b.

Note that you will need to write
```
    py::class_<Bar, std::shared_ptr<Bar>> cls_bar(m, "Bar", cls_foo);
```
and 
```
PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>);
```
(i.e. no ``const``). Using const shared_ptrs as return value or parameter is fine though.
