### ISSUE TITLE
2.2 regression: can not bind member function with lifted access

### ISSUE THREAD

**Issue by lyskov** [pybind/pybind11#1124]
Dear Pybind11 developers, here is another 2.2 regression issue (exact same code was working at a22dd2d 

Right now it seems not possible to bind member function which access was lifter to `public` with `using` declaration. Please see minimal example and error message below.

Thanks,

```C++
#include <pybind11/pybind11.h>

struct Base
{
	void foo() {}
};

class Child : private Base
{
public:
	using Base::foo;
};


PYBIND11_PLUGIN(example) {
    pybind11::module m("example", "pybind11 example plugin");

	pybind11::class_<Child>(m, "Child")
        .def("foo", &Child::foo);

    return m.ptr();

	Child c; c.foo();
}
```

Error:
```
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:1000:93: error: cannot cast private base class 'Base' to 'Child'
auto method_adaptor(Return (Class::*pmf)(Args...)) -> Return (Derived::*)(Args...) { return pmf; }
                                                                                            ^
/home/benchmark/src/pybind11/include/pybind11/pybind11.h:1078:25: note: in instantiation of function template specialization 'pybind11::method_adaptor<Child, void, Base>' requested here
        cpp_function cf(method_adaptor<type>(std::forward<Func>(f)), name(name_), is_method(*this),
                        ^
access-lifting.cpp:20:10: note: in instantiation of function template specialization 'pybind11::class_<Child>::def<void (Base::*)()>' requested here
        .def("foo", &Child::foo);
         ^
access-lifting.cpp:8:15: note: declared private here
class Child : private Base
              ^~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by jagerman** [comment]
On non-MSVC, it's pretty easy to fix by adding a `std::is_convertible<..., ...>` in the appropriate places.  Under MSVC, that doesn't work: `std::is_convertible<Return (Class::*pmf)(Args...)), Return (Derived::*)(Args...)>::value` is `true` even when `Class` is a private base of `Derived`, and I've no idea how to work around that MSVC bug.  (I also tried using `decltype`/`std::declval`, but it similarly acts as if the access violation isn't present).

**Comment by lyskov** [comment]
@jagerman Thank you for looking this up! Will it be possible to merge this into upstream? Unix fix is all i need at the moment...

**Comment by jagerman** [comment]
I worked out a hack for MSVC that seems to fix it there, too (ci tests are still running).  It's in this branch: https://github.com/jagerman/pybind11/tree/method-adaptor-private-fix if you want to try it out.

**Comment by jagerman** [comment]
As far as I can tell, this didn't actually work in pre-2.2; it compiled, but an attempt to call the method would fail:

```C++
#include <pybind11/pybind11.h>
namespace py = pybind11;
class PrivateBase {
public:
    PrivateBase(int v) : v{v} {}
    int f() { return v + 1; }
protected:
    int g() { return v + 2; }
    int v;
};
class PublicDerived : private PrivateBase {
public:
    using PrivateBase::PrivateBase;
    using PrivateBase::f;
    using PrivateBase::g;
    int h() { return v + 3; }
};

PYBIND11_PLUGIN(priv) {
    py::module m("priv");

    py::class_<PublicDerived>(m, "PublicDerived")
        .def(py::init<int>())
        .def("f", &PublicDerived::f)
        .def("g", &PublicDerived::g)
        .def("h", &PublicDerived::h)
        ;

    return m.ptr();
}
```

```
$ python3 -c 'import priv; priv.PublicDerived(1).f()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: f(): incompatible function arguments. The following argument types are supported:
    1. (self: PrivateBase) -> int

Invoked with: <priv.PublicDerived object at 0x7f1454d33600>
```

With my branch the compilation error is avoided, but is basically just punting it to a runtime error.  To be honest, I have no idea how to work around it: what pybind code gets is the base class member function pointer, but that base is inaccessible.  In 2.2, we are (unintentionally!) catching that at compile time because we can't cast the base member function to a derived member function, while in 2.1 we fail at runtime because we can't cast the derived pointer to an (inaccessible) base pointer.  Basically just two sides of the same coin.

**Comment by jagerman** [comment]
The workaround is to use a lambda, e.g.:

```C++
    cl.def("f", [](Derived &self) { return self.f(); });
```

which isn't very nice when you have a bunch of arguments, but I don't see another feasible solution.

**Comment by jagerman** [comment]
#1127 adds a more informative `static_assert`; as I mentioned above, I don't see a way to make this work but at least the error can be more informative.

**Comment by lyskov** [comment]
I see, - thank you for investigating this @jagerman ! I will see if i can detect this during the Binder run and make it fallback to use lambda.

Closing this for now.

**Comment by jagerman** [comment]
Detecting this isn't too difficult: `std::is_base_of<Base, Derived>` will be true but `std::is_convertible<D*, B*>` will be false.  (If you just have the member function pointer, you'll have to deduce `B` first like pybind's `method_adaptor`).

**Comment by jagerman** [comment]
I suppose there might be other cases where that fails, for example with non virtual multiple inheritance with multiple `B` instances, but I'm fairly sure the cast would fail there, too.

**Comment by lyskov** [comment]
Hmm... no i meant detect on different level: detect this when i parse C++11 code (inside Binder) - but i think i might already have code for this.

**Comment by lyskov** [comment]
Or was your suggestion to actually wrap binding code conditional? Thats sounds way too tricky...

**Comment by lyskov** [comment]
Scratch that, i think i am really not sure what you suggesting..

**Comment by jagerman** [comment]
I was thinking from the point of view of having a pointer, like pybind does. That's probably not helpful for you, though, as you pointed out.
